name: CI Deployment to AFaneca Server

on:
  push:
    branches: [ master ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Connecting to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.MYFIN_SSH_HOST }}
        username: ${{ secrets.MYFIN_SSH_USERNAME }}
        key: ${{ secrets.MYFIN_SECRET }}
        port: 22
        script: |
          ./update_myfin.sh
        


